Settings + high_contrast
homedork-se2/Mocked-client pull request #24
Opened 2021-11-07 13:22 UTC by szomer

- Removed irrelevant files reffering to .gitignore
- merged the high_contrast branch and main branch and resolved all conflicts

2021-11-08 09:36 UTC, fannysoderlund requested changes
In the manifest, you accidentally remove the MainActivity and the SettingsActivity, add those back and push again. 
//Edit 11/11 - just checked out this branch and there is something weird here, it doesn't recognize it as an android project in android studio, lets look at it tonight.

2021-11-11 18:10 UTC, malek1017 approved these changes

2021-11-11 18:23 UTC, Nishat7155 approved these changes

2021-11-16 16:04 UTC, szomer commented
Updated the branch code to
- implement the high contrast theme in the settings fragment
- update the manifest to previsouly discussed

2021-11-16 17:46 UTC, fannysoderlund approved these changes
Much nice work. Approved. Just diagrams, but that you can add anytime to comments

2021-11-16 18:56 UTC, merged