Rudimentary function of Pinch zoom added
homedork-se2/Mocked-client pull request #25
Opened 2021-11-09 14:49 UTC by vheyam

Feature added to allow pinch zoom

2021-11-11 13:21 UTC, fannysoderlund requested changes
I have checked out the branch, nice job, don't see how it works on my emulator, but you can show me. However, could you relate this feature to the root_preferences.xml and SettingsFragment, so that this feature can be switched on and off in settings and applied to every activity in the app. We can look at it tonight

2021-11-11 18:10 UTC, malek1017 approved these changes

2021-11-13 17:44 UTC, Nishat7155 approved these changes

2021-11-14 16:04 UTC, Nishat7155 approved these changes

2021-11-15 23:35 UTC, Nishat7155 approved these changes

2021-11-16 13:22 UTC, Nishat7155 approved these changes

2021-11-18 11:00 UTC, vheyam commented
![Untitled Workspace](https://user-images.githubusercontent.com/11834466/142403036-6e8d5951-3bd4-4099-ae69-ff5f224c32f3.png)

2021-11-18 11:52 UTC, vheyam commented
class diagram

![Untitled Workspace (1)](https://user-images.githubusercontent.com/11834466/142410402-ccc82589-f7a9-44cf-83ab-e5c3ba696848.png)

2021-11-21 16:08 UTC, fannysoderlund approved these changes

2021-11-24 10:05 UTC, merged